### ISSUE TITLE
send him/her a email when @him/@her

### ISSUE THREAD

**Issue by YanhaoMo** [julianlam/nodebb-plugin-mentions#88] opened 2016-12-27 05:21 UTC
When I @ someone in NodeBB, I want him/her will receive a email about the mention on his/her offline.
But I haven't found how to config this, Or this has not been implemented yet?
Can you add this feature please?

**Comment by michaelpfaff** [comment] 2017-01-20 03:38
I don't think think this feature currently exists but agree it should be a high priority.

**Comment by julianlam** [comment] 2017-06-21 16:58
Dupe of #75

**Closed by julianlam** 2017-06-21 16:58 UTC
